AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  SuggestExtensions: false


Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
